# Generated by Django 4.2.4 on 2024-03-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="store_manager",
            field=models.BooleanField(default=False),
        ),
    ]
