# Generated by Django 4.2.4 on 2024-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_store_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="customer_id",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Customer ID"
            ),
        ),
    ]
