# Generated by Django 4.2.4 on 2024-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_return_return_id_alter_return_refund_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="return",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved Date"
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rejected Date"
            ),
        ),
    ]
