# Generated by Django 4.2.4 on 2024-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_return_approved_at_alter_return_rejected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewimage",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
