# Generated by Django 4.2.4 on 2024-04-23 14:06

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='refund_status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'PENDING'), (0, 'IN REVIEW'), (2, 'IN TRANSIT'), (3, 'DELIVERED'), (4, 'REFUND INITIATED'), (5, 'REIMBURSED')], default=1, protected=True, verbose_name='Refund Status'),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'PENDING'), (1, 'SUBMITTED'), (2, 'IN REVIEW'), (3, 'APPROVED'), (4, 'REJECTED')], default=0, protected=True, verbose_name='Status'),
        ),
    ]
