# Generated by Django 4.2.4 on 2024-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_products_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Selling Price",
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Stock"),
        ),
    ]
