# Generated by Django 4.2.4 on 2024-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_variant_selling_price_variant_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="rating",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Rating"
            ),
        ),
    ]
