# Generated by Django 4.2.4 on 2024-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_products_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
