# Generated by Django 4.2.4 on 2024-04-21 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_collection_is_in_home_page_lookbook_is_in_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None, verbose_name='Tags'),
        ),
    ]
