# Generated by Django 4.2.4 on 2024-04-24 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_lookbook_variants_lookbookitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='lookbook',
            name='feature_image',
            field=models.FileField(blank=True, null=True, upload_to='lookbook/image', verbose_name='Feature Image'),
        ),
        migrations.AddField(
            model_name='lookbook',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None, verbose_name='Tags'),
        ),
    ]
