# Generated by Django 4.2.4 on 2024-04-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='New Title', max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
