# Generated by Django 4.2.4 on 2024-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="category/images", verbose_name="Image"
            ),
        ),
    ]
