# Generated by Django 4.2.4 on 2024-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Deleted At"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="category",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AlterField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Deleted At"),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Deleted At"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Updated At"),
        ),
    ]
