# Generated by Django 4.2.4 on 2024-04-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0004_returnreason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="second_parent_category",
        ),
        migrations.AddField(
            model_name="category",
            name="is_main_menu",
            field=models.BooleanField(default=False, verbose_name="Main Menu"),
        ),
        migrations.AddField(
            model_name="category",
            name="is_top_category",
            field=models.BooleanField(default=False, verbose_name="Top Category"),
        ),
    ]
