# Generated by Django 4.2.4 on 2024-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=70, verbose_name="Order Id"),
        ),
    ]
