# Generated by Django 4.2.4 on 2024-04-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0009_cart_session_key_alter_cart_user"),
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_order",
                to="customer.cart",
                verbose_name="Cart",
            ),
        ),
    ]
