# Generated by Django 4.2.4 on 2024-04-23 14:06

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'PENDING'), (1, 'PAYMENT INITIATED'), (2, 'ORDER PLACED'), (3, 'ORDER PROCESSING'), (4, 'PACKED'), (5, 'READY FOR DISPATCH'), (6, 'SHIPPED'), (7, 'DELIVERED'), (14, 'CANCELLED')], default=0, protected=True, verbose_name='Status'),
        ),
    ]
